### ISSUE TITLE
Search Button on Dynamic Keyword Page Template-Does not function as expected

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#159] opened 2019-09-18 21:17 UTC
**Page URL**
Page URL: https://test-umb.attune.com/spaces/united-states/arizona/phoenix/classrooms/#top

**Describe the bug**
In the middle of the page, there is a question "looking for another location" with a green "search" button underneath.  When I click the button, it takes me to the top of the page.  I would expect it to open the location/spaces page.

**To Reproduce**

**Expected behavior**
Go to a different page to search or have a search bar open on the current page.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65186492-65ef2400-da2f-11e9-9e14-ece649a1aeee.png)

**Desktop (please complete the following information):**
 - Browser IE 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdsoko** [comment] 2019-09-19 14:27
Duplicate of #122.  Closing this issue.

**Closed by bdsoko** 2019-09-19 14:27 UTC
Labels: Bug
