### ISSUE TITLE
Hotels - Text clipping through box (Charlotte)

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#132] opened 2019-09-17 16:31 UTC
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/north-carolina/charlotte/charlotte-center/visitor-info/
Section: Hotels

**Describe the bug**
Text goes outside box

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65061054-b5095c00-d93e-11e9-9b90-5baa3ed39891.png)

**Additional context**

**Comment by bdsoko** [comment] 2019-09-17 21:28
Duplicate of #123.  All comments will be conveyed there.

**Closed by bdsoko** 2019-09-17 21:28 UTC
Labels: Content
