### ISSUE TITLE
[Blog] 2019: Interlinking - links to mclabs.com

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#14] opened 2019-09-09 16:46 UTC
**Page Info**
https://www.attune.com/insights/blog/posts/2019/february/are-you-too-reliant-on-video-conferencing/

**Describe the bug**
This link on the page "RELATED ARTICLE: Keeping Virtual Attendees Tuned In "  goes to blog.mclabs.com instead of the attune page.

**Screenshots**

**Additional context**

**Comment by esuger** [comment] 2019-09-09 16:47
Also on this page:  https://www.attune.com/insights/blog/posts/2019/april/tricks-to-conquer-language-barriers-in-your-next-meeting/

"RELATED ARTICLE: 5 Tips For Planning the Perfect Training or Meeting for Your Association" goes to blog.mclabs.com

**Comment by esuger** [comment] 2019-09-09 16:48
And this page too:  

https://www.attune.com/insights/blog/posts/2019/april/5-mistakes-not-to-make-when-choosing-a-meeting-venue/
--

**Comment by esuger** [comment] 2019-09-09 16:49
And this one too:   https://www.attune.com/insights/blog/posts/2019/may/measuring-meeting-success-6-key-meeting-kpis-you-should-be-tracking/

**Comment by esuger** [comment] 2019-09-09 16:49
https://www.attune.com/insights/blog/posts/2019/may/crucial-steps-to-reducing-transportation-costs-for-your-next-event/

**Comment by esuger** [comment] 2019-09-09 16:56
Bad links on this page:  https://www.attune.com/insights/blog/posts/2015/december/keeping-learners-from-tuning-out-techniques-for-creating-engaging-virtual-or-hybrid-learning-environment/

**Comment by aj-mclabs** [comment] 2019-09-09 18:04
@esuger Still working on cleaning these up in reverse chronological order. 
2019 blogs should be fixed. Please recheck. Will alert when the next year is set for review.

**Comment by esuger** [comment] 2019-09-09 18:24
Maybe I'm not understanding.   The links are  broken on thes 2019 pages.  

https://www.attune.com/insights/blog/posts/2019/february/are-you-too-reliant-on-video-conferencing/
https://www.attune.com/insights/blog/posts/2019/april/tricks-to-conquer-language-barriers-in-your-next-meeting/
https://www.attune.com/insights/blog/posts/2019/april/5-mistakes-not-to-make-when-choosing-a-meeting-venue/
https://www.attune.com/insights/blog/posts/2019/may/measuring-meeting-success-6-key-meeting-kpis-you-should-be-tracking/
https://www.attune.com/insights/blog/posts/2019/may/crucial-steps-to-reducing-transportation-costs-for-your-next-event/

**Comment by aj-mclabs** [comment] 2019-09-09 19:18
Additional interlinking issues from duplicate thread: 
https://github.com/MicroTekAppDev/Attune.Website.Issues/issues/17

**Comment by connorsli** [comment] 2019-09-11 18:07
@esuger Please recheck all links from 2019 posts. All blogs linked above have been addressed.

**Comment by esuger** [comment] 2019-09-11 18:32
Ebook link on this page still references mclabs.com:   https://www.attune.com/insights/blog/posts/2018/november/4-key-steps-in-a-successful-event-project-implementation-plan/

**Comment by esuger** [comment] 2019-09-11 18:33
Not a new window here:  https://www.attune.com/insights/blog/posts/2018/november/how-to-select-a-training-or-meeting-space-that-works-best-for-your-event/

**Comment by connorsli** [comment] 2019-09-13 20:25
> On this page: https://www.attune.com/insights/blog/posts/2019/may/measuring-meeting-success-6-key-meeting-kpis-you-should-be-tracking/
> 
> Shouldn't the link "RELATED ARTICLE: 12 Meeting Room Essentials That Will Make or Break Your Collab Session" open a new tab/window? It does not.

Links from within blog posts will open in a new tab for everything except other blog posts so that is behaving as intended. We may want to look at having those callout CTAs (related article in this case) open into a new tab but as of now, that is intended.

**Comment by aj-mclabs** [comment] 2019-09-14 20:18
All of these have been fixed with the exception of standardizing link opening behavior (still in progress)
On the final sweep, all internal blog links will not open a new tab. Any internal links to a new type of page will open a new tab. All external links and documents will open a new tab.

**Closed by aj-mclabs** 2019-09-14 20:18 UTC
Labels: Content, Tester Feedback Needed
