### ISSUE TITLE
Hotels - Text clipping through box (St. Louis)

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#130] opened 2019-09-17 16:24 UTC
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/missouri/st-louis/st-louis-center/visitor-info/
Section: Hotel Listing

**Describe the bug**
The print is outside the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65060528-a66e7500-d93d-11e9-9ebd-5ef4883f468b.png)

**Additional context**
this was in IE 11

**Comment by bdsoko** [comment] 2019-09-17 21:28
Duplicate of #123.  All comments will be conveyed there.

**Closed by bdsoko** 2019-09-17 21:28 UTC
Labels: Content
