### ISSUE TITLE
Hotel Slice wording with hotels only by phone

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#141] opened 2019-09-17 20:05 UTC
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-kingdom/scotland/aberdeen/aberdeen-center/visitor-info/

Section: The hotel section for this facility says that we worked hard to negotiate rates and to ask for the Attune rate. There are not "Attune" rates at the hotels that have phone numbers, these are just hotels in the area. The wording should be re-worked.

Suggestion: 
Attune recommends these nearby hotels for your visit. To learn more about the hotel partner please call the number provided.

**Comment by connorsli** [comment] 2019-09-18 15:52
This will be addressed and updates will go in [this thread](https://github.com/MicroTekAppDev/Attune.Website.Issues/issues/143)

**Comment by tomwidel** [comment] 2019-09-18 19:19
Duplicate of #143

**Closed by tomwidel** 2019-09-18 19:19 UTC
Labels: Content
