### ISSUE TITLE
Hotels - Text clipping through box (Edison, NJ)

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#134] opened 2019-09-17 16:55 UTC
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/new-jersey/edison/edison-center/visitor-info/
Section: hotels

**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65062611-0404c080-d942-11e9-8e9e-768d00ff4f1a.png)

**Additional context**
The browser is IE 11

**Comment by bdsoko** [comment] 2019-09-17 21:28
Duplicate of #123.  All comments will be conveyed there.

**Closed by bdsoko** 2019-09-17 21:28 UTC
Labels: Content
