### ISSUE TITLE
[Venue] Dallas: Catering - Grammar #2

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#37] opened 2019-09-09 22:03 UTC
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/maryland/baltimore/baltimore-north-center/
Section: Catering Section. The 3rd word, "accepting", is not correct. It should be "accept"  "Before we accepting a new caterer, we sample the cuisine to ensure it meets our standards."

I just saw that the Louisville page was also incorrect.  I assume this is across all venue pages too.

**Describe the bug**

**Screenshots**

**Additional context**

**Comment by aj-mclabs** [comment] 2019-09-09 22:31
Duplicate of #35

**Closed by aj-mclabs** 2019-09-09 22:31 UTC
Labels: Content
