### ISSUE TITLE
[Visitor] Hotels - Text clipping through box (Duplicate of #46)

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#53] opened 2019-09-11 16:28 UTC
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/maryland/baltimore/baltimore-center/visitor-info/
Section: Hotels

**Describe the bug**
There is text outside the box on the right side "Attune Rate".  Screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/64716045-3ec0b180-d487-11e9-851d-3957bdd8ad93.png)

**Additional context**

**Comment by kopiola** [comment] 2019-09-11 17:37
this is on the Columbia, MD page as well.  It's the same hotel info.

https://test-umb.attune.com/spaces/united-states/maryland/columbia/columbia-center/visitor-info/
--

**Comment by aj-mclabs** [comment] 2019-09-11 18:00
Cannot replicate in Chrome

@kopiola what browser are you using when seeing this?

Reassigned to @bdsoko as a bug

**Comment by aj-mclabs** [comment] 2019-09-11 18:16
Thread locked. This is a duplicate of #46. Please move all discussion on this topic to that thread

**Comment by bdsoko** [comment] 2019-09-16 20:30
Closing this issue as we are using issue #46 to track comments.

**Closed by bdsoko** 2019-09-16 20:30 UTC
Labels: Bug, Tester Feedback Needed
