### ISSUE TITLE
[Homepage] SEO - H Tags

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#156] opened 2019-09-18 19:06 UTC
**Page Info**
https://test-umb.attune.com/

There should only be one H1 on this page. Currently there are three. Please make "Spaces to Train" and "Spaces to Meet" H2 tags (in the banner)

**Comment by connorsli** [comment] 2019-09-19 19:28
Just changing the h1 to h2 messed up the sizing, the CSS class didn't help. I will open up a ticket for Brian to make some CSS tweaks to help out.

**Comment by connorsli** [comment] 2019-09-19 19:35
Ticket opened. You can keep track of the thread here https://github.com/MicroTekAppDev/Attune.Website.Issues/issues/165#issue-495987573

**Comment by bdsoko** [comment] 2019-09-20 14:27
Duplicate of #165.  Closing this issue.

**Closed by bdsoko** 2019-09-20 14:27 UTC
Labels: Content
